import { mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const packageDir = resolve(dirname(__filename), '..');
const distDir = resolve(packageDir, 'dist');
const generatedFile = resolve(distDir, 'generated/lets-ui-styles.js');

const cssPath = fileURLToPath(import.meta.resolve('@lets-ui/styles'));
const css = readFileSync(cssPath, 'utf-8');

rmSync(distDir, { recursive: true, force: true });
mkdirSync(dirname(generatedFile), { recursive: true });
writeFileSync(
  generatedFile,
  `// This file is generated by scripts/build-styles.mjs\n` +
    `export const letsUiStyles = ${JSON.stringify(css)};\n`,
);
